<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Lombiq MSBuild SDK - Orchard Core Theme</Title>
    <Description>MSBuild SDK for Orchard Core themes.</Description>
    <PackageProjectUrl>https://github.com/Lombiq/MSBuild-Targets/blob/dev/Lombiq.MSBuild.OrchardCore.Theme.Sdk/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Lombiq.MSBuild.OrchardCore.Module.Sdk\Sdk\*.*"
          Link="Lombiq.MSBuild.OrchardCore.Module.Sdk\*.*"
          Pack="true"
          PackagePath="Lombiq.MSBuild.OrchardCore.Module.Sdk\"
          Visible="false"/>
  </ItemGroup>

</Project>
