<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!-- Basic configuration -->

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <OrchardCoreProjectType Condition="'$(OrchardCoreProjectType)' == '' ">Module</OrchardCoreProjectType>
  </PropertyGroup>

  <!-- Import core props -->

  <Import Project="$(MSBuildThisFileDirectory)/Lombiq.MSBuild.Core.Targets.props" Condition="'$(NuGetBuild)' == 'true'"/>
  <Import Project="$(MSBuildThisFileDirectory)../Lombiq.MSBuild.Core.Targets/Lombiq.MSBuild.Core.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'"/>

  <!-- External packages -->

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="2.1.0" Condition="'$(OrchardCoreProjectType.Trim().ToUpperInvariant())' == 'MODULE'" />
    <PackageReference Include="OrchardCore.Theme.Targets" Version="2.1.0" Condition="'$(OrchardCoreProjectType.Trim().ToUpperInvariant())' == 'THEME'" />
    <PackageReference Include="OrchardCore.Application.Targets" Version="2.1.0" Condition="$(OrchardCoreProjectType.TrimStart().ToUpperInvariant().StartsWith('APP'))" />
    <PackageReference Include="OrchardCore.ResourceManagement" Version="2.1.0" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="2.1.0" />
  </ItemGroup>

  <!-- Ensure recipes are included -->

  <ItemGroup>
    <EmbeddedResource Update="Recipes\**.recipe.json" Condition="Exists('Recipes')">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
