<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  
  <Choose>
    <When Condition="$(MSBuildProjectName.EndsWith('.Tests')) OR $(MSBuildProjectName.EndsWith('.Samples'))">
      <!-- Adda anything specific to non-publishable projects here. -->
    </When>

    <Otherwise>
      <PropertyGroup>
        <Authors>Lombiq Technologies</Authors>
        <Copyright>Copyright © 2025, Lombiq Technologies Ltd.</Copyright>
        <PackageIcon>NuGetIcon.png</PackageIcon>
        <PackageTags>OrchardCore;Lombiq;AspNetCore</PackageTags>
        <RepositoryUrl>https://github.com/Lombiq/MSBuild-Targets</RepositoryUrl>
        <PackageProjectUrl>https://github.com/Lombiq/MSBuild-Targets</PackageProjectUrl>
        <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
      </PropertyGroup>

      <ItemGroup>
        <None Include="Readme.md" Condition="Exists('Readme.md')" />
        <None Include="NuGetIcon.png" Pack="true" PackagePath="" Condition="Exists('NuGetIcon.png')" />
        <None Include="Sdk\**" Pack="true" PackagePath="Sdk\" Condition="Exists('Sdk')" />
        <None Include="build\**" Pack="true" PackagePath="build\" Condition="Exists('build')" />
      </ItemGroup>
    </Otherwise>
  </Choose>

</Project>
