<Project>
  <Import Project="../Lombiq.MSBuild.OrchardCore.Theme.Sdk/Sdk/Import.props" />

  <ItemGroup>
    <EmbeddedResource Update="wwwroot\Theme.png">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </EmbeddedResource>
  </ItemGroup>
 
  <Import Project="../Lombiq.MSBuild.OrchardCore.Theme.Sdk/Sdk/Import.targets" />
</Project>
