<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!-- Source Generator support for Visual Studio -->

  <Target Name="CustomBeforeCompile" BeforeTargets="Compile" Condition="'$(FromNuGet)' != 'true'">
    <MSBuild Condition="!Exists('$(SourceGeneratorLocation)')"
             Projects="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.SourceGenerators\Lombiq.HelpfulLibraries.SourceGenerators.csproj" />
  </Target>

  <!-- Needed for Azure deployment -->

  <Target Name="AddVendors" AfterTargets="LibraryManagerRestore">
    <ItemGroup>
      <Content Include="wwwroot\vendors\**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
      <EmbeddedResource Include="wwwroot\vendors\**" />
    </ItemGroup>
  </Target>

  <!-- Create a dummy libman.json file if none exists -->

  <Target Name="GenerateNeededFiles" BeforeTargets="BeforeBuild">
    <Copy SourceFiles="$(MSBuildThisFileDirectory)libman.json"
          DestinationFiles="$(ProjectDir)libman.json"
          Condition="!Exists('$(ProjectDir)libman.json')"/>
  </Target>

  <!-- This task captures competing build\{ProjectName}.props files used by NuGet packages and merges their content
       into an intermediate file to use instead, which eliminates packaging conflicts. -->

  <Target Name="NuspecConflictResolution" BeforeTargets="GenerateNuspec">

    <!-- Collect all competing package props file, then remove them from the list to prevent a NuGet warning. -->
    <ItemGroup>
      <PackageProps Include="@(_PackageFiles)" Condition="'%(PackagePath)' == 'build\$(ProjectName).props'" />
      <_PackageFiles Remove="@(_PackageFiles)" Condition="'%(PackagePath)' == 'build\$(ProjectName).props'" />
    </ItemGroup>

    <!-- Concatenate each competing props file into a single mega XML that's still valid, then get the contents inside
         the root elements. -->
    <ReadLinesFromFile File="%(PackageProps.Identity)">
      <Output TaskParameter="Lines" ItemName="PackagePropsFileContents" />
    </ReadLinesFromFile>

    <PropertyGroup>
      <PackagePropsSingleFile>&lt;Projects&gt;@(PackagePropsFileContents, '')&lt;/Projects&gt;</PackagePropsSingleFile>
      <PackagePropsSingleFile>$([System.Text.RegularExpressions.Regex]::Replace($(PackagePropsSingleFile), "xmlns=\u0022[^\u0022]+\u0022", ""))</PackagePropsSingleFile>
    </PropertyGroup>

    <XmlPeek XmlContent="$(PackagePropsSingleFile)" Query="/Projects/Project/*">
      <Output TaskParameter="Result" ItemName="PackagePropsContents" />
    </XmlPeek>

    <!-- Write out the captured elements into a temporary file. -->
    <PropertyGroup>
      <FinalPackagePropsPath>$(IntermediateOutputPath)Package.Build.props</FinalPackagePropsPath>
      <FinalPackagePropsContent>&lt;Project&gt;%0a%0a@(PackagePropsContents, '%0a')%0a%0a&lt;/Project&gt;</FinalPackagePropsContent>
    </PropertyGroup>

    <WriteLinesToFile File="$(FinalPackagePropsPath)" Lines="$(FinalPackagePropsContent)" Overwrite="true" />

    <!-- Register the temporary file as the new, final NuGet props file. -->
    <ItemGroup>
      <_PackageFiles Include="$(FinalPackagePropsPath)"
                     Pack="true"
                     PackagePath="build\$(AssemblyName).props"
                     BuildAction="None" />
    </ItemGroup>

  </Target>

</Project>
