<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq MSBuild Targets - Library Manager</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2025, Lombiq Technologies Ltd.</Copyright>
    <Description>Target for Microsoft Library Manager integration.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;LibMan;LibraryManager</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/MSBuild-Targets</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/MSBuild-Targets</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Readme.md" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
    <None Include="Lombiq.MSBuild.LibMan.Targets.props" Pack="true">
      <PackagePath>build\Lombiq.MSBuild.LibMan.Targets.props</PackagePath>
    </None>
    <None Include="Lombiq.MSBuild.LibMan.Targets.targets" Pack="true">
      <PackagePath>build\Lombiq.MSBuild.LibMan.Targets.targets</PackagePath>
    </None>
  </ItemGroup>

</Project>
