<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!-- Configuration -->

  <PropertyGroup>
    <LombiqHelpfulLibrariesPath Condition="'$(LombiqHelpfulLibrariesPath)' == '' AND Exists('..\..\..\Libraries\Lombiq.HelpfulLibraries')">..\..\..\Libraries\Lombiq.HelpfulLibraries</LombiqHelpfulLibrariesPath>
    <LombiqHelpfulLibrariesPath Condition="'$(LombiqHelpfulLibrariesPath)' == '' AND Exists('..\..\Libraries\Lombiq.HelpfulLibraries')">..\..\Libraries\Lombiq.HelpfulLibraries</LombiqHelpfulLibrariesPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(NuGetBuild)' != 'true'">
    <_SourceGeneratorLocation>$(LombiqHelpfulLibrariesPath)\Lombiq.HelpfulLibraries.SourceGenerators\bin\$(Configuration)\netstandard2.0\Lombiq.HelpfulLibraries.SourceGenerators.dll</_SourceGeneratorLocation>
    <SourceGeneratorLocation Condition="'$(SourceGeneratorLocation)' == '' AND Exists(_SourceGeneratorLocation)">$(_SourceGeneratorLocation)</SourceGeneratorLocation>
  </PropertyGroup>

  <!-- Lombiq Packages -->

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="$(LombiqHelpfulLibrariesPath)\Lombiq.HelpfulLibraries.Attributes\Lombiq.HelpfulLibraries.Attributes.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="true" />
    <ProjectReference Include="$(LombiqHelpfulLibrariesPath)\Lombiq.HelpfulLibraries.SourceGenerators\Lombiq.HelpfulLibraries.SourceGenerators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <!-- Additional files -->

  <ItemGroup>
    <AdditionalFiles Include="libman.json" />
  </ItemGroup>

</Project>
