<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!--  Needed for deployment.  -->
  <Target Name="AddVendors" AfterTargets="LibraryManagerRestore">
    <ItemGroup>
      <Content Include="wwwroot\vendors\**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
  </Target>

</Project>
