<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq MSBuild Targets - Library Manager for Orchard Core Modules</Title>
    <Description>MSBuild target for Microsoft Library Manager integration. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;LibMan;LibraryManager</PackageTags>
    <PackageProjectUrl>https://github.com/Lombiq/MSBuild-Targets/blob/dev/Lombiq.MSBuild.LibMan.Targets/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Lombiq.MSBuild.LibMan.Targets.props" Pack="true" PackagePath="" />
    <None Include="Lombiq.MSBuild.LibMan.Targets.targets" Pack="true" PackagePath="" />
    <None Include="libman.json" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
