<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Lombiq MSBuild SDK - Unit Testing</Title>
    <Description>MSBuild SDK for unit tests using the Lombiq.Tests library.</Description>
    <PackageProjectUrl>https://github.com/Lombiq/MSBuild-Targets/blob/dev/Lombiq.MSBuild.OrchardCore.Tests.Sdk/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Lombiq.MSBuild.Base.Sdk\Sdk\Core.props">
      <Link>Lombiq.MSBuild.Base.Sdk\Core.props</Link>
      <Pack>true</Pack>
      <PackagePath>Lombiq.MSBuild.Base.Sdk/</PackagePath>
      <Visible>false</Visible>
    </None>
    <None Include="..\Lombiq.MSBuild.Base.Sdk\Sdk\Core.targets">
      <Link>Lombiq.MSBuild.Base.Sdk\Core.targets</Link>
      <Pack>true</Pack>
      <PackagePath>Lombiq.MSBuild.Base.Sdk/</PackagePath>
      <Visible>false</Visible>
    </None>
    <None Include="..\Lombiq.MSBuild.Base.Sdk\Sdk\Import.props">
      <Link>Lombiq.MSBuild.Base.Sdk\Import.props</Link>
      <Pack>true</Pack>
      <PackagePath>Lombiq.MSBuild.Base.Sdk/</PackagePath>
      <Visible>false</Visible>
    </None>
    <None Include="..\Lombiq.MSBuild.Base.Sdk\Sdk\Import.targets">
      <Link>Lombiq.MSBuild.Base.Sdk\Import.targets</Link>
      <Pack>true</Pack>
      <PackagePath>Lombiq.MSBuild.Base.Sdk/</PackagePath>
      <Visible>false</Visible>
    </None>
    <None Include="..\Lombiq.MSBuild.Base.Sdk\Sdk\Sdk.props">
      <Link>Lombiq.MSBuild.Base.Sdk\Sdk.props</Link>
      <Pack>true</Pack>
      <PackagePath>Lombiq.MSBuild.Base.Sdk/</PackagePath>
      <Visible>false</Visible>
    </None>
    <None Include="..\Lombiq.MSBuild.Base.Sdk\Sdk\Sdk.targets">
      <Link>Lombiq.MSBuild.Base.Sdk\Sdk.targets</Link>
      <Pack>true</Pack>
      <PackagePath>Lombiq.MSBuild.Base.Sdk/</PackagePath>
      <Visible>false</Visible>
    </None>
  </ItemGroup>

</Project>
