<Project>
  <PropertyGroup>
    <IsLombiqProject Condition="$(MSBuildProjectName.StartsWith('Lombiq.'))">true</IsLombiqProject>
    <LombiqSdkName>Base</LombiqSdkName>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
    <OrchardCoreVersion Condition="'$(OrchardCoreVersion)' == '' AND '$(ManagePackageVersionsCentrally)' != 'true'">3.0.0</OrchardCoreVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="Readme.md" Condition="Exists('Readme.md')" />
    <None Include="..\Readme.md" Condition="!Exists('Readme.md') AND Exists('..\Readme.md')" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" Condition="Exists('NuGetIcon.png')" />
  </ItemGroup>
</Project>
