<Project>
  <PropertyGroup Condition="'$(IsLombiqProject)' == 'true'">
    <Authors Condition="'$(Authors)' == ''">Lombiq Technologies</Authors>
    <CopyrightYear Condition="'$(CopyrightYear)' == ''">20XX</CopyrightYear>
    <Copyright Condition="'$(Copyright)' == ''">Copyright © $(CopyrightYear), Lombiq Technologies Ltd.</Copyright>
    <Description Condition="'$(Description)' == ''">$(Title): $(DescriptionBody) See the project website for detailed documentation.</Description>
    <PackageIcon Condition="Exists('NuGetIcon.png')">NuGetIcon.png</PackageIcon>
    <PackageTags Condition="'$(PackageTags)' == ''">OrchardCore;Lombiq;AspNetCore</PackageTags>
    <PackageProjectUrl Condition="'$(PackageProjectUrl)' == ''">$(RepositoryUrl)</PackageProjectUrl>
  </PropertyGroup>
  
  <!-- Must be separate, because PackageLicenseExpression can't accept a Condition attribute. -->
  <PropertyGroup Condition="'$(IsLombiqProject)' == 'true' AND '$(PackageLicenseExpression)' == ''">
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)LibManIntegration.targets" Condition="'$(UseLibMan)' == 'true'" />
</Project>
