<Project>
  <PropertyGroup>
    <IsLombiqProject Condition="$(MSBuildProjectName.StartsWith('Lombiq.'))">true</IsLombiqProject>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
    <OrchardCoreVersion Condition="'$(OrchardCoreVersion)' == '' AND '$(ManagePackageVersionsCentrally)' != 'true'">3.0.0</OrchardCoreVersion>
  </PropertyGroup>

  <!-- Temporarily disabled "NU1903: Package 'SQLitePCLRaw.lib.e_sqlite3' 2.1.11 has a known high severity
       vulnerability, https://github.com/advisories/GHSA-2m69-gcr7-jv3q" until a newer version is released. -->
  <PropertyGroup>
    <NoWarn Condition="'$(NoWarn)' == ''">NU1903</NoWarn>
    <NoWarn Condition="'$(NoWarn)' != ''">$(NoWarn)%3BNU1903</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="Readme.md" Condition="Exists('Readme.md')" />
    <None Include="..\Readme.md" Condition="!Exists('Readme.md') AND Exists('..\Readme.md')" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" Condition="Exists('NuGetIcon.png')" />
  </ItemGroup>
</Project>