<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!-- Basic configuration -->

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
    <_LombiqMSBuildCoreTargetsImported>true</_LombiqMSBuildCoreTargetsImported>
  </PropertyGroup>

  <!-- NuGet package metadata -->

  <PropertyGroup>
    <Authors Condition="'$(Authors)' == ''">Lombiq Technologies</Authors>
    <PackageIcon Condition="'$(PackageIcon)' == ''">NuGetIcon.png</PackageIcon>
    <PackageTags Condition="'$(PackageTags)' == ''">OrchardCore;Lombiq;AspNetCore</PackageTags>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PackageLicenseExpression)' == ''">
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <None Include="Readme.md" Condition="Exists('Readme.md')" />
    <None Include="..\Readme.md" Link="Readme.md" Condition="!Exists('Readme.md') AND Exists('..\Readme.md')" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <!-- Conditionally import Lombiq projects/packages -->

  <Import Project="$(MSBuildThisFileDirectory)NuGetPackages.props" />

</Project>
