<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq MSBuild Targets - Core</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2025, Lombiq Technologies Ltd.</Copyright>
    <Description>Target for Lombiq-style projects.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/MSBuild-Targets</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/MSBuild-Targets/Lombiq.MSBuild.Core.Targets/Readme.md</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Readme.md" Link="Readme.md" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
    <None Include="build\**" Pack="true" PackagePath="build\" />
    <None Include="Lombiq.MSBuild.Core.Targets.props" Pack="true" PackagePath="" />
    <None Include="NuGetPackages.props" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
