<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!-- Basic configuration -->

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <SolutionTestDir Condition="'$(SolutionTestDir)' == '' AND Exists('..\..\..\..\test')">..\..\..\..\test</SolutionTestDir>
    <SolutionTestDir Condition="'$(SolutionTestDir)' == '' AND Exists('..\..\..\test')">..\..\..\test</SolutionTestDir>
    <ImportLombiqTestsUI Condition="'$(ImportLombiqTestsUI)' == '' AND '$(ImportLombiqTests)' != 'true'">true</ImportLombiqTestsUI>
  </PropertyGroup>

  <!-- Import core props -->

  <Import Project="$(MSBuildThisFileDirectory)../Lombiq.MSBuild.Core.Targets/Lombiq.MSBuild.Core.Targets.props" />

  <!-- External packages -->

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
