<Project>
  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="$(LombiqSolutionRootPath)\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Lombiq.Tests.UI.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.Tests.UI" Version="14.2.2-alpha.7.osoe-925" />
  </ItemGroup>
</Project>