<Project>
  <PropertyGroup>
    <LombiqSdkName>OrchardCore.Tests.UI</LombiqSdkName>
  </PropertyGroup>
  
  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="$(LombiqSolutionRootPath)\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Lombiq.Tests.UI.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.Tests.UI">
      <Version Condition="'$(ManagePackageVersionsCentrally)' != 'true'">14.2.2-alpha.16.osoe-925</Version>
    </PackageReference>
  </ItemGroup>
</Project>