<Project>
  <PropertyGroup>
    <LombiqSdkName>OrchardCore.Module</LombiqSdkName>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <UseLibMan Condition="'$(UseLibMan)' == '' AND Exists('libman.json')">true</UseLibMan>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)LibManIntegration.props" Condition="'$(UseLibMan)' == 'true'" />

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets">
      <Version Condition="'$(ManagePackageVersionsCentrally)' != 'true'">$(OrchardCoreVersion)</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Recipes\*.recipe.json">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup Condition="'$(FromNuGet)' != 'true'">
    <ProjectReference Include="$(LombiqHelpfulLibrariesPath)/Lombiq.HelpfulLibraries.OrchardCore/Lombiq.HelpfulLibraries.OrchardCore.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(FromNuGet)' == 'true'">
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore">
      <Version Condition="'$(ManagePackageVersionsCentrally)' != 'true'">12.6.1-alpha.9.osoe-925</Version>
    </PackageReference>
  </ItemGroup>
</Project>
