<Project>
  <Import Project="$(MSBuildThisFileDirectory)../../Lombiq.MSBuild.LibMan.Targets/Lombiq.MSBuild.LibMan.Targets.props"
          Condition="'$(FromNuGet)' != 'true'"/>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.LibraryManager.Build">
      <Version Condition="'$(ManagePackageVersionsCentrally)' != 'true'">3.0.114</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(FromNuGet)' == 'true'">
    <PackageReference Include="Lombiq.MSBuild.LibMan.Targets">
      <Version Condition="'$(ManagePackageVersionsCentrally)' != 'true'">1.0.1-alpha.15.osoe-1208</Version>
    </PackageReference>
    <PackageReference Include="Lombiq.HelpfulLibraries.Attributes" OutputItemType="Analyzer" ReferenceOutputAssembly="true">
      <Version Condition="'$(ManagePackageVersionsCentrally)' != 'true'">12.6.1-alpha.9.osoe-925</Version>
    </PackageReference>
    <PackageReference Include="Lombiq.HelpfulLibraries.SourceGenerators" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
      <Version Condition="'$(ManagePackageVersionsCentrally)' != 'true'">12.6.1-alpha.9.osoe-925</Version>
    </PackageReference>
  </ItemGroup>
</Project>