<Project Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk/2.1.1-alpha.1.osoe-1308">

  <PropertyGroup>
    <IsLombiqProject>true</IsLombiqProject>
    <Title>Lombiq MSBuild SDK Sample</Title>
    <CopyrightYear>2026</CopyrightYear>
    <DescriptionBody>Example Description.</DescriptionBody>
    <RepositoryUrl>https://github.com/Lombiq/MSBuild-Targets/</RepositoryUrl>
  </PropertyGroup>

</Project>
