<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Lombiq MSBuild SDK - Base</Title>
    <Description>Base SDK for other Lombiq MSBuild SDKs. Don't use this directly.</Description>
    <PackageProjectUrl>https://github.com/Lombiq/MSBuild-Targets/blob/dev/Lombiq.MSBuild.OrchardCore.Base.Sdk/Readme.md</PackageProjectUrl>
  </PropertyGroup>

</Project>
