<Project>
  <!-- You can't set the target framework inside a NuGet package because that information is used to find it in the
       first place, so setting TargetFramework only makes sense when this SDK is imported from submodule. -->
  <PropertyGroup>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net10.0</TargetFramework>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)Core.props" />
</Project>